version: '0.1'

services:
  wordpress:
    image: wordpress
    container_name: wordpressServer
    restart: unless-stopped
    ports:
      - "81:80"
    depends_on:
      - mysql
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=leffet_lune
      - WORDPRESS_TABLE_PREFIX=lili_
    volumes:
      - ./wp-content/:/var/www/html/wp-content/
      # - ./wp-content/themes/:/var/www/html/wp-content/themes/
      # - ./wp-content/plugins/:/var/www/html/wp-content/plugins/
      # - ./wp-content/uploads/:/var/www/html/wp-content/uploads/
  mysql:
    image: mariadb
    container_name: serverMySQLWordpress
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "3304:3306"
    volumes:
      - ./database/data/:/var/lib/mysql/
      - ./database/backup/:/var/backup/
      # - ./database/leffet-lune.sql:/docker-entrypoint-initdb.d/leffet-lune.sql
  phpmyadmin:
    image: phpmyadmin
    container_name: serverPHPMyAdminWordpress
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
    ports:
      - "8084:80"